###ANALYSIS OPTIONS###

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2,
# strandedness). Units are biological replicates. If the column "strandedness" is present (which is optional),
# can be empty or has one of these values: none, yes or reverse. none is for unstranded
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse`
# which is referenced in STAR manual section 7, "Counting number of reads per gene".
units: units.tsv

#Allow trimming and alignment params to be specified by libtype
trimming:
  # skip trimming: false or true
  skip: false
  #NEB ultra directional II adapter sequence -- I'm using this for now while I wait to hear back about ovation adaptor
  adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  ovation:
    trimmed_dir: cutadapt_trimmed

params:
  star: ''
  cutadapt-se: '-m 1'
  cutadapt-pe: '-m 1'
  kallisto:
    ovation: '-l 1 -s 1 --single --fr-stranded'
  #sf_method = c('ratio','poscounts', 'iterate')
  #use poscounts for testing with small dataset, otherwise ratio

###INDEX BUILDING OPTIONS###

# Create annotations and index files for the NMJ 4SU timecourse experiment
genome_name: dmel_628
spike_name: elex
index_name: dmel_628_elex

#https://www.ensembl.org/info/data/ftp/index.html
genome_fasta_address: ftp://ftp.ensembl.org/pub/release-99/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.28.dna.toplevel.fa.gz
genome_gtf_address: ftp://ftp.ensembl.org/pub/release-99/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.99.gtf.gz
cdna_fasta_address: ftp://ftp.ensembl.org/pub/release-99/fasta/drosophila_melanogaster/cdna/Drosophila_melanogaster.BDGP6.28.cdna.all.fa.gz
ncrna_fasta_address: ftp://ftp.ensembl.org/pub/release-99/fasta/drosophila_melanogaster/ncrna/Drosophila_melanogaster.BDGP6.28.ncrna.fa.gz
sirv_zip_address: https://www.lexogen.com/wp-content/uploads/2018/08/SIRV_Set1_Sequences_170612a-ZIP.zip
ercc_fasta_address: https://www-s.nist.gov/srmors/certificates/documents/SRM2374_putative_T7_products_NoPolyA_v2.FASTA

include_sirvs: True
include_erccs: True

#If only using a subset of the ERCCs list here. If empty and include_erccs, then include all
ercc_subset:
  - ERCC-00057
  - ERCC-00073
  - ERCC-00077
  - ERCC-00104
  - ERCC-00112
  - ERCC-00142
  - ERCC-00150
  - ERCC-00162
  - ERCC-00165
  - ERCC-00168

build_star_params:
  genomeSAsparseD: 4
  genomeSAindexNbases: 10
  limitGenomeGenerateRAM: 12000000000

###FOURSU TIMEPONT OPTIONS###
#labeling time, in hours
labeling_time: 0.25

#if model_subset == True, then INSPEcT will only fit rates for 20 genes
#This is to make testing faster because the fitting step takes ages..
model_subset: False

#If remove_spike_inspect == True, then remove the spike-ins prior to the INSPEcT modeling
remove_spike_inspect: True

#foursu timepoint options (map t number to timepoint in stress response (in hrs))
#for Josh's NMJ timepoints, this was 15 min of labeling ending at t(min) = 0, 51, 91, 136, 181
foursu_timepoints:
  1: 0
  2: 0.85
  3: 1.517
  4: 2.267
  5: 3.017
