###ANALYSIS OPTIONS###

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2,
# strandedness). Units are biological replicates. If the column "strandedness" is present (which is optional),
# can be empty or has one of these values: none, yes or reverse. none is for unstranded
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse`
# which is referenced in STAR manual section 7, "Counting number of reads per gene".
units: units.tsv

#Allow trimming and alignment params to be specified by libtype
trimming:
  # skip trimming: false or true
  skip: False
  #NEB ultra directional II adapter sequence -- I'm using this for now while I wait to hear back about ovation adaptor
  #Use adapters for TruSeq as recommended by Nugen
  #https://support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html?langsel=/us/
  adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
  adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
  ovation:
    trimmed_dir: cutadapt_trimmed

params:
  star: ''
  cutadapt-se: '-m 1'
  cutadapt-pe: '-m 1'
  kallisto:
    ovation: ''
  #sf_method = c('ratio','poscounts', 'iterate')
  #use poscounts for testing with small dataset, otherwise ratio

###INDICES###
# Create annotations and index files for the NMJ 4SU timecourse experiment
kallisto_index: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/foursu_test1/indices/kallisto_index/dmel_628_elex.idx
star_index: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/foursu_test1/indices/star_index_dmel_628_elex
gtf_file: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/foursu_test1/indices/combo_files/dmel_628_elex.gtf
txt_2_gene_file: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/foursu_test1/indices/combo_files/dmel_628_elex_txt2gene.txt

###FOURSU TIMEPONT OPTIONS###
#TxDb to use in R
txt_db_R: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/nmj_results/results_20818/annotations/dmel_628_elex.sqlite

#labeling time, in hours
labeling_time: 0.25

#if model_subset == True, then INSPEcT will only fit rates for 20 genes
#This is to make testing faster because the fitting step takes ages..
model_subset: False

#If remove_spike_inspect == True, then remove the spike-ins prior to the INSPEcT modeling
remove_spike_inspect: True

#Exclude the following experiments from INSPECT analysis.
#If none, use one dash to signify empty list instead of nonetype.
exps_excluded_from_inspect:
  -
#foursu timepoint options (map t number to timepoint in stress response (in hrs))
#for Josh's NMJ timepoints, this was 15 min of labeling ending at t(min) = 0, 51, 91, 136, 181
foursu_timepoints:
  1: 0
  2: 0.85
  3: 1.517
  4: 2.267
  5: 3.017
