###ANALYSIS OPTIONS###

# units.csv = path or URL to sequencing unit sheet (CSV format, columns: sample,
# replicate, condition, RNAtype, fq1, fq2).
# replicate = biological replicate.
# RNAtype = input or pd
# condition = genotype or an integer that will map to a timepoint.
units: units.csv
skip_trimming: False

#Provide program parameters by libtype.
#Adapter1_3p is used for read1 and single-end. Adapter2_3p is used for read2.
#Use the trimmed_dir to get snakemake to use cutadapt or bbtrim (QuantSeq only)
params:
  trimming:
    ovation:
      trimmed_dir: 'trimmed'
    neb_dirII:
      trimmed_dir: 'trimmed'
    quantseq:
      trimmed_dir: 'bb_trimmed'
  bbtrim:
    quantseq:
      se: 'k=13 ktrim=r useshortkmers=t mink=5 qtrim=r trimq=10 minlength=20'
  cutadapt:
    ovation:
      se: '-m 1'
      pe: '-m 1'
      adapter1_3p: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
      adapter2_3p: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
    neb_dirII:
      se: '-m 1'
      pe: '-m 1'
      adapter1_3p: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
      adapter2_3p: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
  star:
    ovation:
      se: ''
      pe: ''
    neb_dirII:
      se: ''
      pe: ''
    quantseq:
      se: ''
      pe: ''
  kallisto:
    ovation:
      se: '-l 1 -s 1 --single --fr-stranded'
      pe: ''
    neb_dirII:
      se: '-l 1 -s 1 --single --rf-stranded'
      pe: ''
    quantseq:
      se: '-l 1 -s 1 --single --fr-stranded'
      pe: ''

###INDICES###
# Annotations and index files for the NMJ 4SU timecourse experiment
kallisto_index: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/foursu_test1/indices/kallisto_index/dmel_628_elex.idx
star_index: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/foursu_test1/indices/star_index_dmel_628_elex
gtf_file: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/foursu_test1/indices/combo_files/dmel_628_elex.gtf
txt_2_gene_file: /Users/maryk.thompson/Desktop/Davislab/OneDriveNexus365/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/foursu_test1/indices/combo_files/dmel_628_elex_txt2gene.txt
rrna_gene_file: /Users/mkthompson/Desktop/Davislab/3.4_NMJ_4Tu_4sU/3.4e_pipeline_dev/test_genome_build1/sequences/rrna/rrna_genes.csv
#parameters for by gene expression summary
#choose the average or median transcript length
feature_length_method: median

#choose between length and eff_length (effective length) for TPM calculation
feature_length_column: length

#labeling time, in hours
labeling_time: 0.25

#if model_subset == True, then INSPEcT will only fit rates for 20 genes
#This is to make testing faster because the fitting step takes ages..
model_subset: False
#Set model seed to 1 for reproducibility, set seed to NULL for random
#Seed is only used for functional version of modeling.
#DOES NULL get converted to NULL with snakemake ->R?
model_seed: 1
#If model_rates_nonfunctional == True, use the non-functional INSPEcT modeling.
model_rates_nonfunctional: False

#If remove_spike_inspect == True, then remove the spike-ins prior to the INSPEcT modeling
#If remove_rRNA_inspect == True, then remove the rRNAs prior to the INSPEcT analysis
remove_spike_inspect: True
remove_rrna_inspect: True

#Exclude the following experiments from INSPECT analysis.
#If none, use one dash to signify empty list instead of nonetype.
exps_excluded_from_inspect:
  -

kinetic_analysis_type: steadystate
#kinetic_analysis_type: timecourse

#foursu timepoint options (map t number to timepoint in response (in hrs))
#for Josh's NMJ timepoints, this was 15 min of labeling ending at
#t(min) = 0, 51, 91, 136, 181
#foursu_condition_mapping:
#  1: 0
#  2: 0.85
#  3: 1.517
#  4: 2.267
#  5: 3.017

foursu_condition_mapping:
  - wt
